#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

cd "$(dirname "$0")/.."   # 始终在仓库根目录执行

ENV_FILE="${TMPDIR:-/tmp}/ccps-acceptance-wizard.env"  # 断点续跑状态，不进仓库
RESULTS=()                  # "标签|结论|备注" 行
SANDBOX="${TMPDIR:-/tmp}/ccps-accept-sandbox"
DATE=$(date +%F)
RESULTS_MD="docs/acceptance/real-machine-results-${DATE}.md"

# capture KEY "标签" — 记录一个验收段的结论（pass/fail/skip）与备注。
capture() {
  local key="$1" label="$2" v n
  ask "${key}_V" "$label — 结论 [pass/fail/skip]:"
  ask "${key}_N" "$label — 失败项/备注（无则回车）:"
  eval "v=\"\$${key}_V\"; n=\"\$${key}_N\""
  v="${v:-skip}"
  write_env "${key}_V" "$v"
  write_env "${key}_N" "$n"
  RESULTS+=("${label}|${v}|${n:-—}")
}

banner "CCPS 真机验收（issue #87）"

# ── 1. 环境体检与元数据 ─────────────────────────────────────────────────
stage "环境体检与元数据"
say "确认本机环境能跑真实验收：最新构建、ccps 指向本仓库、claude CLI、VS Code。"
MACHINE="$(uname -m) / macOS $(sw_vers -productVersion 2>/dev/null || echo '?')"
NODE_VERSION=$(node --version)
CCPS_VERSION=$(node -p "require('./package.json').version")
HEAD_SHA=$(git rev-parse --short HEAD)
note "日期 $DATE · 机器 $MACHINE · Node $NODE_VERSION · ccps $CCPS_VERSION · HEAD $HEAD_SHA"

say "构建最新 dist（保证验收的是当前分支代码）…"
if ! npm run build >/dev/null 2>&1; then
  warn "npm run build 失败 — 先解决构建问题再验收。"; exit 1
fi
say "✓ dist 已构建"

CCPS_BIN="$(command -v ccps || true)"
DIST_REAL="$(node -e "process.stdout.write(require('fs').realpathSync('./dist/index.js'))")"
CCPS_REAL=""
[[ -n "$CCPS_BIN" ]] && CCPS_REAL="$(node -e "process.stdout.write(require('fs').realpathSync(process.argv[1]))" "$CCPS_BIN" 2>/dev/null || true)"
if [[ "$CCPS_REAL" == "$DIST_REAL" ]]; then
  say "✓ ccps 已链接到本仓库 dist"
elif confirm "ccps 未指向本仓库 dist（当前: ${CCPS_REAL:-未安装}）。执行 npm link？"; then
  npm link >/dev/null 2>&1 && say "✓ npm link 完成" || { warn "npm link 失败"; exit 1; }
else
  warn "未链接 — 后续阶段的 ccps 可能是旧版，验收结论将不可信。"
  SKIPPED+=("ccps 未链接到本仓库 dist")
fi

if command -v claude >/dev/null 2>&1; then
  say "✓ claude CLI: $(command -v claude)"
else
  warn "PATH 上没有 claude — 启动链阶段（L / T9 / V5）无法真跑。"
  SKIPPED+=("claude CLI 缺失，真启动阶段需手记")
fi

if [[ -d "/Applications/Visual Studio Code.app" ]]; then
  say "✓ VS Code 已安装"
else
  warn "未找到 VS Code.app — 编辑器接力（E）与 VS Code 终端（V）阶段受影响。"
fi

case "$NODE_VERSION" in
  v22.*|v24.*) ;;
  *) warn "本机 Node $NODE_VERSION 不在验收矩阵（22/24 LTS）内 — 结果将注明此偏差（CI 已覆盖矩阵）。";;
esac

ask EXECUTOR "执行人姓名："
write_env EXECUTOR "$EXECUTOR"

# ── 2. 验收沙箱（夹具 profile 树）────────────────────────────────────────
stage "验收沙箱（夹具 profile 树）"
say "在 $SANDBOX 生成带 CJK/emoji 名等病理样本的夹具 app home —"
say "渲染类检查全在沙箱做，不碰真实的 ~/.cc-profile-switch。"
if npm run fixtures:generate -- --tier baseline --pathologies all --out "$SANDBOX/.cc-profile-switch" >/dev/null 2>&1; then
  say "✓ 夹具 app home 已生成（baseline 档 20 profiles × 50 skills + 全部病理样本）"
else
  warn "夹具生成失败 — 渲染检查改用真实 home 进行，并把此问题记进备注。"
fi
step "搜索检查需要一个名字含 stu 的 profile，在沙箱里建一个："
if ! env HOME="$SANDBOX" USERPROFILE="$SANDBOX" ccps create study --template study >/dev/null 2>&1; then
  env HOME="$SANDBOX" USERPROFILE="$SANDBOX" ccps init >/dev/null 2>&1 || true
  env HOME="$SANDBOX" USERPROFILE="$SANDBOX" ccps create study --template study >/dev/null 2>&1 \
    || warn "沙箱建 study profile 失败 — 到时在真实 home 里任选一个 profile 做搜索检查。"
fi
say "沙箱用法：在任意终端执行  HOME=$SANDBOX ccps tui"
note "真实启动链（Stage 6）也可用真实 home：直接 ccps tui。"
pause "沙箱就绪，回车继续"

# ── 3. §1.3 Terminal.app ─────────────────────────────────────────────────
stage "§1.3 Terminal.app（T1–T10）"
say "下面每步都在新开的 Terminal.app 窗口里做，做完回来填结论。"
open -a Terminal 2>/dev/null || note "自动打开失败 — 请手动打开 Terminal.app"
step "新窗口执行：HOME=$SANDBOX ccps tui"
step "T1 正常进入 Workbench；T2 退出后无残留输出（Alternate Screen 进出干净）"
step "T3 侧边树里 CJK 名（如「研究代理」「✨-emoji-skill」）宽度对齐不错位；T4 emoji 名不破坏布局"
step "T5 拖动窗口边角缩放，布局实时重排"
step "T6 缩到 80×24：界面降级但可操作，破坏性确认不被截断"
step "T7 退出后执行 NO_COLOR=1 HOME=$SANDBOX ccps tui — 完全可操作，信息不只靠颜色"
step "T8 按 / 输入 stu → 树过滤；esc 清除"
step "T9 选中 study 按 l：Claude 真启动（显示登录页也正常），环境指向沙箱 profile"
step "T10 在 Claude 里 /exit → Workbench 恢复并显示退出闪存"
capture T "§1.3 Terminal.app T1–T10"

# ── 4. §1.4 VS Code 集成终端 ─────────────────────────────────────────────
stage "§1.4 VS Code 集成终端（V1–V6，macOS 半边）"
open -a "Visual Studio Code" 2>/dev/null || note "自动打开失败 — 请手动打开 VS Code"
step "在 VS Code 里打开集成终端（Ctrl+\`），执行 HOME=$SANDBOX ccps tui"
step "V1 正常进入；V2 Alternate Screen 进出干净；V3 CJK 渲染正确"
step "V4 拖动面板缩放，布局实时重排"
step "V5 按 l 启动 Claude 正常；V6 /exit 后 Workbench 恢复并显示闪存"
capture V "§1.4 VS Code 终端 V1–V6"

# ── 5. Ghostty 冒烟（额外）───────────────────────────────────────────────
stage "Ghostty 冒烟（额外，非清单门禁）"
say "Ghostty 不在 #79 清单里，但它是日常终端 — 这里出问题就是真实信号。"
open -a Ghostty 2>/dev/null || note "自动打开失败 — 请手动打开 Ghostty"
step "HOME=$SANDBOX ccps tui：进入/退出干净、CJK/emoji 对齐、缩放重排"
step "NO_COLOR=1 下可操作；/ 搜索 stu 正常；l 启动 + /exit 恢复"
capture G "Ghostty 冒烟（额外）"

# ── 6. §2 启动/恢复链 ────────────────────────────────────────────────────
stage "§2 启动/恢复链（真 Claude spawn，L1–L7）"
step "cd 到一个真实项目目录（有 .claude/ 更好），执行 ccps tui（真实 home）"
step "L7+L4 按 d 看 dry-run 计划：cwd=当前目录、CLAUDE_CONFIG_DIR 指向该 profile 的 claude-home、无 --add-dir；macOS 上 spawn 命令前缀应为 script -q /dev/null"
step "L1–L3 按 l 真启动：Claude 内的项目目录就是当前目录"
step "L5 在 Claude 里 /exit → Workbench 恢复，显示成功闪存（SIGCHLD 路径）"
step "L6(信号) 再启动一次；另开终端 pgrep -f claude 找到刚起的 PID，kill -TERM <pid> → Workbench 恢复并显示中断闪存（#88 新文案「Claude was interrupted」）"
step "L6(数字码，可选) mkdir -p /tmp/claude-shim && printf '#!/bin/sh\\nexit 3\\n' > /tmp/claude-shim/claude && chmod +x /tmp/claude-shim/claude，然后 PATH=/tmp/claude-shim:\$PATH ccps tui 启动 → 恢复时显示「Claude exited (3)」；测完 rm -rf /tmp/claude-shim"
capture L "§2 启动/恢复链 L1–L7"

# ── 7. §4 编辑器接力 ─────────────────────────────────────────────────────
stage "§4 编辑器接力（E1–E6）"
step "沙箱 Workbench 里选中一个资源文件，按 e → VS Code 打开它（E1）"
step "返回 Workbench：该资源出现 ✎ watching 徽标（E2）"
step "在 VS Code 改一行保存 → 预览刷新并带 updated HH:MM:SS 时间戳（E3）"
step "在另一终端把该文件改名 → Workbench 显示 missing + 警告（E4）"
step "改回原名 → watching 恢复（E5）"
step "E6（VS Code 不可用 → 内联报错+回退选项）：回退路径有单测 test/workbench-edit-fallback.test.tsx 覆盖；VS Code 已装时记 N/A 并在备注写明即可。想真测：临时把 VS Code.app 改名再按 e（自行权衡，测完改回）"
capture E "§4 编辑器接力 E1–E6"

# ── 8. §5 CJK 渲染 ───────────────────────────────────────────────────────
stage "§5 CJK 渲染（K1–K6）"
say "在任一真实终端的沙箱 Workbench 里观察（P8 病理样本已含 CJK/emoji 名）："
step "K1–K3 CJK 名 East Asian Width 对齐；描述里的中文不破坏卡片布局"
step "K4 emoji 名不错位、不在字符中间截断"
step "K5 界面 chrome 只用 BMP 字符（● ✓ ⚠ ✗），无 emoji"
step "K6 按 ? 打开帮助表，用其中的语言项切到中文 → 全界面中文渲染正常"
capture K "§5 CJK 渲染 K1–K6"

# ── 9. §7 性能复测 ───────────────────────────────────────────────────────
stage "§7 性能复测（本机真硬件）"
note "本机 Node ${NODE_VERSION}（矩阵为 22/24 LTS）— 数字注明偏差；矩阵由 CI 覆盖。"
if confirm "现在跑 perf harness（baseline 20 次 + 3x 10 次，约一两分钟）？"; then
  PERF_OK=1
  npm run perf:harness -- --tier baseline --iterations 20 --out docs/acceptance/baseline-perf.json || PERF_OK=0
  npm run perf:harness -- --tier 3x --iterations 10 --out docs/acceptance/3x-perf.json || PERF_OK=0
  if [[ "$PERF_OK" == "0" ]]; then
    warn "perf harness 未正常完成 — 记为 fail，备注写明现象。"
    ask PERF_MANUAL_N "备注："
    RESULTS+=("§7 性能复测（baseline+3x）|fail|harness 运行失败：${PERF_MANUAL_N:-见终端输出}")
  else
    PERF_OUT=$(node -e "
      const b=require('./docs/acceptance/baseline-perf.json');
      const t=require('./docs/acceptance/3x-perf.json');
      const m=Object.fromEntries(b.measurements.map(x=>[x.name,x.p95Ms]));
      const tmax=Math.max(...t.measurements.map(x=>x.maxMs));
      const ok=b.verdict.overallPass&&t.verdict.overallPass;
      process.stdout.write((ok?'pass':'fail')+'|baseline p95: cold-start '+m['cold-start']+'ms / keystroke '+m['keystroke-repaint']+'ms / search '+m['search-filter']+'ms / content-search '+m['content-search']+'ms；3x 单操作 max '+tmax.toFixed(2)+'ms（Node '+process.version+'）');
    ")
    PERF_V="${PERF_OUT%%|*}"; PERF_N="${PERF_OUT#*|}"
    say "$PERF_N"
    RESULTS+=("§7 性能复测（baseline+3x）|${PERF_V}|${PERF_N}")
  fi
else
  capture PERF "§7 性能复测"
fi

# ── 10. Windows 部分、裁决与落盘 ─────────────────────────────────────────
stage "Windows 部分、裁决与落盘"
say "以下只能在 Windows 真机做：§1.1 W1–W10（Windows Terminal）、§1.2 C1–C4（conhost）、"
say "§3 J1–J4（junction 语义）、P2（ACL 仅当前用户）、§1.4 的 Windows 半边。"
if confirm "这轮有 Windows 机器可做这些吗？"; then
  step "Windows 机上：clone 仓库 → 切 feature/profile-workbench → npm ci && npm run build && npm link"
  step "按 docs/acceptance/real-machine-checklist.md 的 §1.1 / §1.2 / §1.4 / §3 / §6-P2 逐项过，结果填进清单表"
  step "（本向导是 bash 脚本，git-bash 下也能在 Windows 上重跑）"
  RESULTS+=("Windows 部分（§1.1/§1.2/§3/P2/V-win）|pending-external|macOS 侧已完成；Windows 侧待真机执行")
else
  RESULTS+=("Windows 部分（§1.1/§1.2/§3/P2/V-win）|deferred|本轮无 Windows 机器 — #87 保持开启直到完成或 owner 显式接受")
fi

MAC_V="PASS"; for row in "${RESULTS[@]}"; do case "$row" in *"|fail|"*) MAC_V="FAIL";; esac; done

{
  printf '# Real-Machine Acceptance Results — %s\n\n' "$DATE"
  printf -- '- Executor: %s\n' "$EXECUTOR"
  printf -- '- Machine: %s\n' "$MACHINE"
  printf -- '- Node: %s（验收矩阵 22/24 LTS，偏差已注明；矩阵由 CI 覆盖）\n' "$NODE_VERSION"
  printf -- '- ccps: %s @ %s（branch feature/profile-workbench）\n' "$CCPS_VERSION" "$HEAD_SHA"
  printf -- '- Source: issue #87 / docs/acceptance/real-machine-checklist.md\n\n'
  printf '| Section | Verdict | Notes |\n|---|---|---|\n'
  for row in "${RESULTS[@]}"; do printf '| %s |\n' "${row//|/ | }"; done
  printf '\n**macOS-side verdict: %s**\n' "$MAC_V"
} > "$RESULTS_MD"
say "✓ 结果已写入 $RESULTS_MD"

# ──────────────────────────────────────────────────────────────────────────

finish
say "下一步："
step "复核 $RESULTS_MD 并补备注；需要存档就自行 git add（向导不替你提交）"
step "把结果贴到 #87：~/.local/bin/ghr issue comment 87 --repo wubq511/cc-profile-switch --body-file $RESULTS_MD"
step "#87 在 Windows 侧完成（或你显式接受豁免）前保持开启；#87 关闭后 #89 才解锁"
